name: last_fm
description: A simple app to demonstrate a good architecture with flutter_bloc, hive, and REST API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  functional_enum_annotation: ^1.2.2
  get_it: ^7.2.0
  go_router: ^2.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  pretty_dio_logger: ^1.1.1
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^8.4.0
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  functional_enum: ^1.1.4
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "assets/images/icon_ios.png"
  image_path_android: "assets/images/icon_android.png"